### ISSUE TITLE
Update the righty sample_info.txt file

### ISSUE THREAD

**Issue by jasper-tms** [mindyxkim/righty-alignment#3]
I know this isn't alignment but you keep forgetting about this. Do it by June 10th (the week after the Berlin conference) or I'll tell Creme to pee on everything you own.

```
vi /n/groups/htem/temcagt/datasets/righty_r1062/sample_info.txt
```

**Comment by mindyxkim** [comment]
The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky's fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was stained with the enhanced rOTO protocol (1% buffered OsO4 staining on ice for 90 minutes, 1% TCH 8-minute incubation at 40 degrees C, 2% unbuffered OsO4 staining at room temperature for 60 minutes, 1% UA at 4 degrees C overnight). On the next day, the sample was dehydrated in a graded ethanol series, washed with propylene oxide, infiltrated with 2:1 and 1:2 propylene oxide:LX 112 resin consequtively for 30 minutes each, then placed in pure resin overnight at 4 degrees C. On the following day, the sample was embedded in fresh pure resin and was then cured at 60 degrees C for 48 hours.

**Comment by jasper-tms** [comment]
Was righty a cross between Canton-S males and w1118 females, or Canton-S females and w1118 males? It probably doesn't matter but for the sake of having everything written down, might as well write this down if you have the info.

**Comment by jasper-tms** [comment]
And do you know if righty grew up at 25°C or at room temperature?

**Comment by mindyxkim** [comment]
Lefty: CS male, w1118 female
Righty: w1118b male, CS female
They were at room temperature.

^ information from Ryan

**Comment by jasper-tms** [comment]
Thanks!

The current text in `sample_info.txt` on o2 is

> The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky's fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was stained with the enhanced rOTO protocol (1% buffered OsO4 in A-TRA staining on ice for 90 minutes, 1% TCH 8-minute incubation at 40 degrees C, 2% unbuffered OsO4 staining at room temperature for 60 minutes, 1% UA at 4 degrees C overnight). On the next day, the sample was dehydrated in a graded ethanol series, washed with propylene oxide, infiltrated with 2:1 and 1:2 propylene oxide:LX 112 resin consequtively for 30 minutes each, then placed in pure resin overnight at 4 degrees C. On the following day, the sample was embedded in fresh pure resin and was then cured at 60 degrees C for 48 hours.

I had two comments for you you [on slack](https://htem.slack.com/archives/DM4Q9S4UE/p1655131896023409):

> this isn't the enhanced rOTO protocol. the enhanced rOTO protocol has separate osmium and reducing agent steps, and has a step where the sample is heated up for like 2 hrs while in UA

so I think dropping "the enhanced rOTO protocol (" from the prep info would be fine.

> I would give more details on the A-TRA staining step, as they give in the FAFB paper. you wash with A-TRA in buffer a few times before staining with osmium and A-TRA in buffer i think?

Do you have the info available on what the exact steps were?

**Comment by jasper-tms** [comment]
> Righty: w1118b male, CS female

is the `b` there a typo? If not, what is `w1118b`?

**Comment by mindyxkim** [comment]
yes, it's a typo from ryan. thanks for catching that.

**Comment by mindyxkim** [comment]
> Thanks!
> 
> The current text in `sample_info.txt` on o2 is
> 
> > The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky's fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was stained with the enhanced rOTO protocol (1% buffered OsO4 in A-TRA staining on ice for 90 minutes, 1% TCH 8-minute incubation at 40 degrees C, 2% unbuffered OsO4 staining at room temperature for 60 minutes, 1% UA at 4 degrees C overnight). On the next day, the sample was dehydrated in a graded ethanol series, washed with propylene oxide, infiltrated with 2:1 and 1:2 propylene oxide:LX 112 resin consequtively for 30 minutes each, then placed in pure resin overnight at 4 degrees C. On the following day, the sample was embedded in fresh pure resin and was then cured at 60 degrees C for 48 hours.
> 
> I had two comments for you you [on slack](https://htem.slack.com/archives/DM4Q9S4UE/p1655131896023409):
> 
> > this isn't the enhanced rOTO protocol. the enhanced rOTO protocol has separate osmium and reducing agent steps, and has a step where the sample is heated up for like 2 hrs while in UA
> 
> so I think dropping "the enhanced rOTO protocol (" from the prep info would be fine.
> 
> > I would give more details on the A-TRA staining step, as they give in the FAFB paper. you wash with A-TRA in buffer a few times before staining with osmium and A-TRA in buffer i think?
> 
> Do you have the info available on what the exact steps were?

yes i do:
- wash specimen with 0.02M A-TRA in caco buffer (3x10min)
- stain specimen in 1% OsO4, 0.1M A-TRA (90min on ice)

**Comment by jasper-tms** [comment]
I'd like to add the sample prep information as a page on https://github.com/jasper-tms/righty/wiki. Could you provide an updated version of the sample prep paragraph above that includes the updates we were talking about?

**Comment by mindyxkim** [comment]
> I'd like to add the sample prep information as a page on https://github.com/jasper-tms/righty/wiki. Could you provide an updated version of the sample prep paragraph above that includes the updates we were talking about?

The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky's fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was washed with 0.02M 3-amino-1,2,4-triazole (A-TRA) in cacodylate buffer (3x10min) and then stained with 1% OsO4 in 0.1M A-TRA for 90min on ice. On the next day, the sample was dehydrated in a graded ethanol series, washed with propylene oxide, infiltrated with 2:1 and 1:2 propylene oxide:LX 112 resin consequtively for 30 minutes each. The sample was then placed in pure resin overnight at 4 degrees and was embedded in fresh pure resin on the following day. The resin block was cured at 60 degrees C for 48 hours.

**Comment by jasper-tms** [comment]
Why did the TCH, second Os, and UA steps disappear?

**Comment by mindyxkim** [comment]
> Why did the TCH, second Os, and UA steps disappear?

sorry copying error

The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky's fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was washed with 0.02M 3-amino-1,2,4-triazole (A-TRA) in cacodylate buffer (3x10min) and then stained with 1% OsO4 in 0.1M A-TRA for 90min on ice. On the same day, the sample was stained with 1% thiocarbohydrazide for 8min at 40 degrees C, 2% unbuffered OsO4 at room temperature for 60 minutes, and 1% UA at 4 degrees C overnight. On the next day, the sample was stained with lead aspartate for 3 hours at 60 degrees C and was then dehydrated in a graded ethanol series, washed with propylene oxide, and infiltrated with 2:1 and 1:2 propylene oxide:LX 112 resin consecutively for 30 minutes each. The sample was then placed in pure resin overnight at 4 degrees and was embedded in fresh pure resin on the following day. The resin block was cured at 60 degrees C for 48 hours.

**Comment by jasper-tms** [comment]
Why did a lead aspartate step just appear?

**Comment by mindyxkim** [comment]
The fly was pinned onto a dissection pad, ventral-side up. The fly was then submerged in a drop of ice cold Karnovsky’s fixative (2.5% formaldehyde, 2.5% glutaraldehyde in 0.1M cacodylate buffer, pH 7.4) containing 0.04% CaCl2. First, its legs and proboscis were removed to allow fixative to access the nervous tissue. Next, its head capsule and cuticle of the ventral thorax were carefully removed to expose the nervous tissue for extraction. Within 5 minutes, the brain and connected VNC were completely dissected and transferrd to an Eppendorf tube containing the same fixative. The sample was then kept at 4 degrees C overnight. On the subsequent day, the sample was washed with 0.02M 3-amino-1,2,4-triazole (A-TRA) in cacodylate buffer (3x10min) and then stained with 1% OsO4 in 0.1M A-TRA for 90min on ice. On the same day, the sample was stained with 1% thiocarbohydrazide for 8min at 40 degrees C, 2% unbuffered OsO4 at room temperature for 60 minutes, and 1% UA at 4 degrees C overnight. On the next day, the sample was stained with lead aspartate for 3 hours at 60 degrees C and was then dehydrated in a graded ethanol series, washed with 100% propylene oxide, and infiltrated with 2:1 propylene oxide:LX 112 resin for an hour. The sample was then placed in 1:2 propylene oxide:LX 112 resin overnight at 4 degrees and was embedded in fresh pure resin on the following day. The resin block was cured at 60 degrees C for 48 hours.

**Comment by jasper-tms** [comment]
Photos from @mindyxkim of her protocol (from 9/28 experiment):

![IMG_2273](https://user-images.githubusercontent.com/23616964/201494924-9f44db21-ba0f-4977-8680-d70f6adc18a9.jpg)

![IMG_2274](https://user-images.githubusercontent.com/23616964/201494926-8ecf0965-4a0d-458b-a02b-93d4567545d1.jpg)

![IMG_2275](https://user-images.githubusercontent.com/23616964/201494952-3b742157-e033-44be-b3e6-038b5a008618.jpg)

![IMG_2276](https://user-images.githubusercontent.com/23616964/201494974-feae40cb-5101-4783-81f7-254c99236d0e.jpg)

![IMG_2277](https://user-images.githubusercontent.com/23616964/201494977-cbc9e28a-098f-48b5-a9cf-4556aabbb236.jpg)

![IMG_2278](https://user-images.githubusercontent.com/23616964/201494982-a6681de4-1cc7-4e0d-8aab-576232a9507f.jpg)

Photo of her notes from 10/26 dissections:
![Image from iOS](https://user-images.githubusercontent.com/23616964/201494986-feeeaa8f-f60f-4c78-806b-0cb63e501c49.jpg)
